version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"         # path where settings.gradle is
    schedule:
      interval: "daily"   # or "daily", "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "cbelloda"
    assignees:
      - "cbelloda"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
    # Enable security updates
    insecure-external-code-execution: "allow"
    # Don't ignore security updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      # Allow security updates through
      - dependency-name: "!*"
        update-types: ["security"]
